### PR TITLE
Test hot fix

### LINKED ISSUE #14: SimpleTest TEST macro no work for greater than comparison
The TEST macro doesn't use the op  parameter.

https://github.com/neotericpiguy/QDmrconfig/blob/f6b37d2ccd7cf9d765338c3decd902f98045a320/src/tests/SimpleTest/SimpleTest.hpp#L8L11

### PR DESCRIPTION
**Pull request by neotericpiguy**
Boo boo made in the macro to close #14

### CODE REVIEW

File: src/tests/SimpleTest/SimpleTest.hpp [hunk 1]
```diff
@@ -6,7 +6,7 @@
 #include <vector>
 
 #define TEST(lparam, op, rparam)                            \
-  if (lparam == rparam)                                     \
+  if (lparam op rparam)                                     \
```
Comment (neotericpiguy) [inline src/tests/SimpleTest/SimpleTest.hpp:9]: Man this looks weird, but what ev.
